# Generated by Django 3.1.3 on 2020-11-13 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0007_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
